name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
        repository: ngageoint/opensphere-yarn-workspace
        path: opensphere-yarn-workspace
        persist-credentials: false
